import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import ServerSideNav from '@/components/ServerSideNav'
import { PlayerProvider } from './context/PlayerContext'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='dark'>
          <ServerSideNav />
          <PlayerProvider>
          <SessionProvider>
           {children}
          </SessionProvider>
          </PlayerProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
